buildscript {
    repositories {
        google()
        mavenCentral()
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
}

repositories {
    google()
    mavenCentral()
    maven {
        url 'https://artifact.bytedance.com/repository/pangle/'
    }
}

dependencies {
    implementation 'com.google.ads.mediation:inmobi:10.8.7.0'
	implementation 'com.google.ads.mediation:facebook:6.20.0.0'	
	implementation 'com.google.ads.mediation:pangle:7.5.0.2.0'
    implementation 'com.google.ads.mediation:applovin:13.3.1.1'
}